# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiniAspire' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MiniAspire

  # Required by RNFirebase
  pod 'Firebase/Core'

  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end
